//reducer資料重置
export const SET_PAGE_RESET = 'SET_PAGE_RESET';
export const SET_COURSE_RESET = 'SET_COURSE_RESET';
//header-老師名稱、所有課程
export const SET_TEACHER_DATA = 'SET_TEACHER_DATA';
export const TEACHER_DATA_REQUEST = 'TEACHER_DATA_REQUEST';
export const TEACHER_DATA_FAIL = 'TEACHER_DATA_FAIL';
//header-是否已新增課程
export const ADD_COURSE_DATA_FINISH = 'ADD_COURSE_DATA_FINISH';
export const ADD_COURSE_DATA_UNDONE = 'ADD_COURSE_DATA_UNDONE';
//課程的週次資料
export const SET_COURSEWEEKS_DATA = 'SET_COURSEWEEKS_DATA';
export const COURSEWEEKS_DATA_REQUEST = 'COURSEWEEKS_DATA_REQUEST';
export const COURSEWEEKS_DATA_FAIL = 'COURSEWEEKS_DATA_FAIL';
//專注統計頁-上課時段紀錄
export const SET_CLASSROOM_TIME_STATUS = 'SET_CLASSROOM_TIME_STATUS';
export const TIME_STATUS_REQUEST = 'TIME_STATUS_REQUEST';
export const TIME_STATUS_FAIL = 'TIME_STATUS_FAIL';
//專注統計頁-排行榜
export const SET_RANK_DATA = 'SET_RANK_DATA';
export const RANK_DATA_REQUEST = 'RANK_DATA_REQUEST';
export const RANK_DATA_FAIL = 'RANK_DATA_FAIL';
//專注統計頁-全班專注平均資料
export const SET_CLASSROOM_CONCERN_INFO = 'SET_CLASSROOM_CONCERN_INFO';
export const CLASSROOM_CONCERN_INFO_REQUEST = 'CLASSROOM_CONCERN_INFO_REQUEST';
export const CLASSROOM_CONCERN_INFO_FAIL = 'CLASSROOM_CONCERN_INFO_FAIL';
//專注統計頁-學生資料
export const SET_STUDENT_CONCERN_INFO = 'SET_STUDENT_CONCERN_INFO';
export const STUDENT_CONCERN_INFO_REQUEST = 'STUDENT_CONCERN_INFO_REQUEST';
export const STUDENT_CONCERN_INFO_FAIL = 'STUDENT_CONCERN_INFO_FAIL';
//點名系統頁-課堂人數統計
export const SET_ROLLCALL_STATUS = 'SET_ROLLCALL_STATUS';
export const ROLLCALL_STATUS_REQUEST = 'ROLLCALL_STATUS_REQUEST';
export const ROLLCALL_STATUS_FAIL = 'ROLLCALL_STATUS_FAIL';
export const ROLLCALL_START = 'ROLLCALL_START';
export const ROLLCALL_FINISH = 'ROLLCALL_FINISH';
//學生名單頁-取得已登錄的學生名單
export const CLASSMATES_DATA_REQUEST = 'CLASSMATES_DATA_REQUEST';
export const SET_CLASSMATES_DATA = 'SET_CLASSMATES_DATA';
export const SET_CLASSMATES_FAILLIST = 'SET_CLASSMATES_FAILLIST';
export const CLASSMATES_DATA_FAIL = 'CLASSMATES_DATA_FAIL';
//完整點名頁
export const TOTALROLLCALL_DATA_REQUEST = 'TOTALROLLCALL_DATA_REQUEST';
export const SET_TOTALROLLCALL_WEEK_DATA = 'SET_TOTALROLLCALL_WEEK_DATA';
export const SET_TOTALROLLCALL_LIST_DATA = 'SET_TOTALROLLCALL_LIST_DATA';
export const TOTALROLLCALL_DATA_FAIL = 'TOTALROLLCALL_DATA_FAIL';
//登入頁面
export const BEGIN_DATA_REQUEST = 'BEGIN_DATA_REQUEST';
export const SUCCESS_DATA_REQUEST = 'SUCCESS_DATA_REQUEST';
export const FAIL_DATA_REQUEST = ' FAIL_DATA_REQUEST';
