//header-老師名稱、所有課程
export const SET_TEACHER_DATA = 'SET_TEACHER_DATA';
export const TEACHER_DATA_REQUEST = 'TEACHER_DATA_REQUEST';
export const TEACHER_DATA_FAIL = 'TEACHER_DATA_FAIL';
//專注統計頁-上課時段紀錄
export const SET_CLASSROOM_TIME_STATUS = 'SET_CLASSROOM_TIME_STATUS';
export const TIME_STATUS_REQUEST = 'TIME_STATUS_REQUEST';
export const TIME_STATUS_FAIL = 'TIME_STATUS_FAIL';
//專注統計頁-排行榜
export const SET_RANK_DATA = 'SET_RANK_DATA';
export const RANK_DATA_REQUEST = 'RANK_DATA_REQUEST';
export const RANK_DATA_FAIL = 'RANK_DATA_FAIL';
//專注統計頁-全班專注平均資料
export const SET_CLASSROOM_CONCERN_INFO = 'SET_CLASSROOM_CONCERN_INFO';
export const CLASSROOM_CONCERN_INFO_REQUEST = 'CLASSROOM_CONCERN_INFO_REQUEST';
export const CLASSROOM_CONCERN_INFO_FAIL = 'CLASSROOM_CONCERN_INFO_FAIL';
//專注統計頁-學生資料
export const SET_STUDENT_CONCERN_INFO = 'SET_STUDENT_CONCERN_INFO';
export const STUDENT_CONCERN_INFO_REQUEST = 'STUDENT_CONCERN_INFO_REQUEST';
export const STUDENT_CONCERN_INFO_FAIL = 'STUDENT_CONCERN_INFO_FAIL';
//點名系統頁-課堂人數統計
export const SET_ROLLCALL_STATUS = 'SET_ROLLCALL_STATUS';
export const BEGIN_DATA_REQUEST = 'BEGIN_DATA_REQUEST';
export const SUCCESS_DATA_REQUEST = 'SUCCESS_DATA_REQUEST';
export const FAIL_DATA_REQUEST = ' FAIL_DATA_REQUEST';