export const SET_CLASSROOM_TIME_STATUS = 'SET_CLASSROOM_TIME_STATUS';
export const SET_ROLLCALL_STATUS = 'SET_ROLLCALL_STATUS';
export const BEGIN_DATA_REQUEST = 'BEGIN_DATA_REQUEST';
export const SUCCESS_DATA_REQUEST = 'SUCCESS_DATA_REQUEST';
export const FAIL_DATA_REQUEST = ' FAIL_DATA_REQUEST';